### ISSUE TITLE
Component does not update the model since upgrading to RC6

### ISSUE THREAD

**Issue by seustachi** [pleerock/ng2-rating#5]
The  rating component is not updating the model since RC6.

If I replace the form module to use the old one, it works.
"@angular/forms": "0.3.0",

**Comment by pleerock** [comment]
are you sure about it? did you install latest 0.0.6 version? checkout commits, I made an upgrade to rc.6

**Comment by seustachi** [comment]
I have the last version, 0.0.6.

Yes I am sure. I was puzzle at first, but by just reverting the angular form module, it works again.

I would be glad to offer more info, but there is no error message, and it is quite complicated to produce a minimal project to demonstrate the issue

**Comment by pleerock** [comment]
I just checked it with angular rc.6 and latest rc.6 forms, works good. Show me your error logs

**Comment by seustachi** [comment]
I could narrow down the problem. It happens only if the component is inside a <form>.

In your samples there is no form,

**Comment by seustachi** [comment]
I have build a minimalist project from https://github.com/mgechev/angular2-seed

and I am now certain there is an issue. Unfortunately there is no error message I can share with you.

**Comment by seustachi** [comment]
Last update : my problem is fixed by updating to rc7 ! 
Form component had several bugs, probably one of them is the culprit : 
https://github.com/angular/angular/blob/master/CHANGELOG.md
 Thanks for the good work on this component
