### ISSUE TITLE
Support AoT Compilation

### ISSUE THREAD

**Issue by shaneog** [pleerock/ng2-rating#6]
Would be great to support [Ahead-of-Time](https://angular.io/docs/ts/latest/cookbook/aot-compiler.html) (AoT) compilation.

**Comment by bonnici** [comment]
Angular2 and angular-cli specifically are really pushing AoT so this module doesn't work in the latest angular-cli and might not work for many seeds in the near future. Here is a nice resource about how to get the library AoT-ready: https://medium.com/@isaacplmann/getting-your-angular-2-library-ready-for-aot-90d1347bcad#.9o2cu6mpr. I tried cloning the repo and going through it but I'm new to library development so I got a bit lost. I might give it another go a bit later.

**Comment by pleerock** [comment]
added in `0.0.7`
